### ISSUE TITLE
neo-storm compile avm testinvoke error on neo-python. 

### ISSUE THREAD

**Issue by BlackTrace** [CityOfZion/neo-storm#35]
### Description of the issue
neo-storm compile avm testinvoke error on neo-python. 
![image](https://user-images.githubusercontent.com/8064316/46211484-377fc100-c366-11e8-851c-ad269d06b1a4.png)

avm:
https://cdn.discordapp.com/attachments/409613754016464907/495164763974926337/main.avm
golang:
https://cdn.discordapp.com/attachments/409613754016464907/495164733155180545/main.go
### Type (put an `x` sign in the square brackets)
- [ ] bug report

**Comment by anthdm** [comment]
@BlackTrace This should now be fixed with the latest version rc-6
