### ISSUE TITLE
Concatenated strings log as bytearray instead of string

### ISSUE THREAD

**Issue by Pega88** [CityOfZion/neo-storm#39]
### Description of the issue
Logging single strings or variables are runtime logged as readable text. Once you combine them, they are logged as byte array making debugging harder.

### Type (put an `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS
OS X 10.13.6
* Go version
1.11.1
* Release tag/commit of the code
f93a28ef87d272a74f821d45ae0c6735a8c610be
tag: 1.0.0-rc

### Expected behaviour
What should happen?
I'd expect to have a concatenated string also be logged in runtime as readable string.
### Actual behaviour
it's being logged as bytearray, while simple strings/vars are logged as readable text

### Steps to reproduce
run snippet:

```Golang
func Main(val int) int{
	runtime.Log("logging a string")
	text := "logging a variable"
	runtime.Log(text)
	runtime.Log("trying to combine this with " + text)
	return val
}
```

output will be 
"logging a string"
"logging a variable"
and the last log will be bytearray instead of readable text.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by anthdm** [comment]
Thanks for the report will take a look as soon as possible! Bug and feature reports always appreciated!
