### ISSUE TITLE
Else in if else cases is always executed

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-storm#41]
### Description of the issue
Briefly describe the issue you are experiencing.

### Type (put an `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* macOS high sierra
* go version go1.10 darwin/amd64
* master branch

### Expected behaviour
Consider the following 2 contract examples

```go
func Main(operation string, args []interface{}) bool {
	if operation == "parrot" {
		repeatMe := args[0].(string)
		runtime.Notify(repeatMe)
	} else {
		runtime.Notify("Hello World")
	}

	return true
}
```

```go
func Main(operation string, args []interface{}) bool {
	if operation == "parrot" {
		repeatMe := args[0].(string)
		runtime.Notify(repeatMe)
	}

	if operation != "parrot" {
		runtime.Notify("Hello World")
	}

	return true
}
```

both should run exactly the same:
- return arg[0] if operation == "parrot""
- return hello world if not

### Actual behaviour
The second example runs as expected, but the first always returns hello world, even if the operation is "parrot"

### Steps to reproduce
1. compile both contracts
2. testinvoke

**Comment by anthdm** [comment]
@jeroenptrs There is a new branch `development` which should include a fix for this.

**Comment by anthdm** [comment]
This is solved in latest release
