### ISSUE TITLE
Assigning to a slice element does not work

### ISSUE THREAD

**Issue by fyrchik** [CityOfZion/neo-storm#45]
### Description of the issue
Seems like assigning to a slice element does not produce any changes to the slice (see code below).

### Type (put an `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* Linux Mint 19 Tara
* go version go1.11 linux/amd64
* master

### Expected behaviour
`a` should change accordingly

### Actual behaviour
`a` remains unchanged

### Steps to reproduce
invoke SC with this Main
```
func Main(op string, args []interface{}) interface{} {
    a := []byte("abc")
    runtime.Notify(a)
    a[1] = a[0]
    a[2] = 0
    runtime.Notify(a)
    return a
}
```

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by anthdm** [comment]
However @fyrchik:

For bytearrays this will not work, this is due to the VM.

stack for array is 
```
memory[array[1, 2 ,3], otherstackitem, otherstackitem]
``` 

stack for bytearray is 
```
memory[bytearray("abc"), otherstackitem, otherstackitem]
``` 

You can clearly see that there is no option for bytearrays to manipulate individual bytes.

**Comment by anthdm** [comment]
After some more research I found that there is no way to do index operations on `bytearrays` due to the NEO VM is not supporting this.

However there is already an issue raised for this:
(https://github.com/neo-project/neo-vm/issues/59)

And the already existing PR:
(https://github.com/neo-project/neo-vm/pull/60)

**Comment by igormcoelho** [comment]
Thanks for pointing this out @anthdm ! I believe neo-vm PR is already solving the issue, as we will be able to manually convert between arrays/bytearrays and do all sorts of operations ;)

**Comment by fyrchik** [comment]
@anthdm This is not a big issue, I can use array of uint32 in my case :)

**Comment by anthdm** [comment]
@fyrchik That is nice to hear!

**Comment by anthdm** [comment]
I will close this issue for now. This should be automatically fixed when the NEO VM has fixed/solved this problem. We can reopen this issue if this problem persists after.

**Comment by igormcoelho** [comment]
@anthdm this was partially solved directly on C# neo-compiler: https://github.com/neo-project/neo-compiler/commit/d6e18710a43b1fbd83452f6a3e3f8e8bb5b7fa98
