### ISSUE TITLE
shifts on integers don't work

### ISSUE THREAD

**Issue by fyrchik** [CityOfZion/neo-storm#47]
### Description of the issue
I need to perform shifts on integer numbers. However, I get a compiler error (see below).

### Type (put an `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS linux mint 19 Tara
* go version go1.11 linux/amd64
* master

### Expected behaviour
Contract compiles.

### Actual behaviour
Compiler error `NEO-GO-VM > compiler don't know how to convert this basic type: {4 uint 3}`

### Steps to reproduce
Compile following contract:
```
func Main() int {
    a := 1
    a = a << 3
    return a
}
```

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by anthdm** [comment]
@fyrchik The latest release candidate has support for this.
