### ISSUE TITLE
bitwise operations (AND, XOR) don't work

### ISSUE THREAD

**Issue by fyrchik** [CityOfZion/neo-storm#48]
### Description of the issue
I can't perform bitwise operations (AND, XOR) on integers.

### Type (put an `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS Linux Mint 19 Tara
* go version go1.11 linux/amd64
* master

### Expected behaviour
AND is performed accordingly (as I can see, there is an opcode in VM here https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/OpCode.cs)

### Actual behaviour
Compiler error `NEO-GO-VM > compiler could not convert token: &`
(in case of XOR `NEO-GO-VM > compiler could not convert token: ^`)

### Steps to reproduce
Try to compile following smartcontract:
```
func Main() int {
    a := 3
    a = 0x0F & a
    return a
}
```

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by anthdm** [comment]
@fyrchik I released a new candidate which includes support for this. Can you check this out?
